import type { InvestigationObject, ObjectPreset } from '../types/investigation'

export const initialObjects: InvestigationObject[] = [
  {
    id: 'obj-dossier',
    name: 'Dokumen Rahasia',
    desc: 'Berkas dossier investigasi kasus nomor #102.',
    notes:
      'Dossier ini berisi rekaman transaksi mencurigakan tertanggal 12 September 2026. Analisis stempel forensik menunjukkan dokumen ini dipalsukan.',
    isInspected: false,
    type: 'box',
    position: [-1.2, 1.3, 0.3],
    rotation: [0, 0.25, 0],
    scale: [1, 1, 1],
    color: '#f59e0b',
    roughness: 0.5,
    metalness: 0.1,
    args: [0.75, 0.08, 0.95],
  },
  {
    id: 'obj-crystal',
    name: 'Artefak Kristal TKP',
    desc: 'Sampel kristal mineral nomor bukti #09 ditemukan di TKP.',
    notes:
      'Sampel mineral anomali memancarkan resonansi cahaya ringan. Diduga berasal dari fasilitas sintesis material laboratorium.',
    isInspected: true,
    type: 'octahedron',
    position: [0, 1.45, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    color: '#38bdf8',
    roughness: 0.1,
    metalness: 0.8,
    args: [0.28],
  },
  {
    id: 'obj-safe',
    name: 'Brankas Mini Digital',
    desc: 'Penyimpanan bukti digital dengan kunci enkripsi.',
    notes:
      'Brankas biometrik portabel terkunci rapat. Port USB di sisi kanan menunjukkan ada percobaan ekstraksi data sebelum tersangka kabur.',
    isInspected: false,
    type: 'box',
    position: [1.2, 1.45, -0.3],
    rotation: [0, -0.35, 0],
    scale: [1, 1, 1],
    color: '#3b82f6',
    roughness: 0.2,
    metalness: 0.85,
    args: [0.65, 0.45, 0.55],
  },
]

export const objectPresets: ObjectPreset[] = [
  {
    type: 'box',
    name: 'Koper Bukti Forensik',
    desc: 'Koper alumunium berisi alat forensik TKP.',
    notes: 'Koper milik tim identifikasi, berisi kit uji luminol dan pemindai serbuk sidik jari.',
    color: '#64748b',
    args: [0.8, 0.25, 0.6],
    roughness: 0.3,
    metalness: 0.7,
  },
  {
    type: 'cylinder',
    name: 'Tabung Sampel Kimia',
    desc: 'Tabung silinder cairan bukti kimiawi.',
    notes: 'Cairan hijau pekat mengandung zat akseleran pembakaran.',
    color: '#10b981',
    args: [0.12, 0.12, 0.45, 32],
    roughness: 0.1,
    metalness: 0.5,
  },
  {
    type: 'sphere',
    name: 'Sensor Digital TKP',
    desc: 'Orbe sensor pemindai 3D portabel.',
    notes: 'Alat pemindai lidar yang merekam posisi millimeter tiap serpihan di TKP.',
    color: '#a855f7',
    args: [0.22, 32, 32],
    roughness: 0.1,
    metalness: 0.9,
  },
  {
    type: 'capsule',
    name: 'Kapsul Bukti Nanotech',
    desc: 'Kapsul penyimpan microchip bukti.',
    notes: 'Microchip terenkripsi tingkat tinggi ditemukan tersembunyi di bawah lantai.',
    color: '#ec4899',
    args: [0.12, 0.3, 16, 32],
    roughness: 0.2,
    metalness: 0.6,
  },
  {
    type: 'box',
    name: 'Kotak Arsip Dokumen',
    desc: 'Kardus penyimpanan berkas perkara lampau.',
    notes: 'Berkas kasus lama yang dibuka kembali karena adanya kesamaan pola sidik jari.',
    color: '#d97706',
    args: [0.6, 0.4, 0.5],
    roughness: 0.8,
    metalness: 0.05,
  },
  {
    type: 'octahedron',
    name: 'Permata Bukti Sitaan',
    desc: 'Batu permata bernilai tinggi dari brankas.',
    notes: 'Hasil penyelundupan permata ilegal yang belum terdaftar di bea cukai.',
    color: '#ef4444',
    args: [0.25],
    roughness: 0.1,
    metalness: 0.95,
  },
]
